/**
 * Report rendering — terminal, JSON and Markdown.
 *
 * Deterministic, generated from rule output. No model paraphrases the
 * findings: a summariser would reintroduce exactly the drift this tool exists
 * to catch.
 *
 * Colour is used, but never alone — every finding carries its severity as a
 * word, so the report survives a pipe, a CI log and a colour-blind reader.
 */

import type { DiffResult } from '../diff/index.js';
import type { Finding, Severity, Snapshot } from '../model/types.js';
import { computeHealth, formatHealthLines, type Health } from './health.js';

const ANSI = {
  reset: '[0m',
  bold: '[1m',
  dim: '[2m',
  red: '[31m',
  yellow: '[33m',
  blue: '[34m',
  grey: '[90m',
};

const useColour = () =>
  process.stdout.isTTY && !process.env.NO_COLOR && process.env.TERM !== 'dumb';

const paint = (s: string, code: string) => (useColour() ? `${code}${s}${ANSI.reset}` : s);

const SEVERITY_LABEL: Record<Severity, string> = {
  error: 'ERROR',
  warn: 'WARN ',
  info: 'INFO ',
};

const SEVERITY_COLOUR: Record<Severity, string> = {
  error: ANSI.red,
  warn: ANSI.yellow,
  info: ANSI.blue,
};

export interface ReportInput {
  snapshot: Snapshot;
  findings: Finding[];
  diff?: DiffResult;
  skipped?: { id: string; why: string }[];
  staleDays?: number;
}

export function renderTerminal(input: ReportInput): string {
  const { snapshot, findings, diff, skipped = [] } = input;
  const health = computeHealth(snapshot, input.staleDays);
  const lines: string[] = [];

  // Suspicious changes come first. A daily reader should see them in the first
  // ten lines or the tool has failed.
  if (diff && diff.suspicious.length) {
    lines.push(paint(ANSI.bold + 'SUSPICIOUS CHANGES', ANSI.red));
    lines.push(paint(`  ${diff.from.slice(0, 10)} → ${diff.to.slice(0, 10)}`, ANSI.grey));
    lines.push('');
    for (const f of diff.suspicious.slice(0, 20)) lines.push(...findingLines(f));
    if (diff.suspicious.length > 20) {
      lines.push(paint(`  … and ${diff.suspicious.length - 20} more`, ANSI.grey));
    }
    lines.push('');
  } else if (diff) {
    lines.push(paint('No suspicious changes.', ANSI.grey));
    lines.push('');
  }

  const bySeverity: Record<Severity, Finding[]> = { error: [], warn: [], info: [] };
  for (const f of findings) bySeverity[f.severity].push(f);

  for (const severity of ['error', 'warn', 'info'] as const) {
    const group = bySeverity[severity];
    if (!group.length) continue;
    lines.push(
      paint(`${SEVERITY_LABEL[severity].trim()}S (${group.length})`, SEVERITY_COLOUR[severity] + ANSI.bold)
    );
    lines.push('');
    for (const f of group) lines.push(...findingLines(f));
    lines.push('');
  }

  if (!findings.length) {
    lines.push(paint('No findings.', ANSI.grey));
    lines.push('');
  }

  // Per-rule counts, so a rule going silent is visible.
  const perRule = countByRule(findings);
  if (Object.keys(perRule).length) {
    lines.push(paint('BY RULE', ANSI.bold));
    for (const [rule, n] of Object.entries(perRule).sort()) {
      lines.push(`  ${rule}  ${n}`);
    }
    lines.push('');
  }

  if (skipped.length) {
    lines.push(paint('NOT RUN', ANSI.bold));
    for (const s of skipped) lines.push(paint(`  ${s.id}  ${s.why}`, ANSI.grey));
    lines.push('');
  }

  lines.push(paint('CORPUS HEALTH', ANSI.bold));
  for (const l of formatHealthLines(health)) lines.push(`  ${l}`);
  lines.push('');
  lines.push(
    paint(
      '  Counts, not a score. A percentage would invite optimising the number\n' +
        '  instead of the history, and would flatten the thin/strong distinction\n' +
        '  the corpus exists to preserve.',
      ANSI.grey
    )
  );

  return lines.join('\n');
}

function findingLines(f: Finding): string[] {
  const where = [f.collection, f.slug, f.field].filter(Boolean).join(' / ');
  const head =
    `  ${paint(SEVERITY_LABEL[f.severity], SEVERITY_COLOUR[f.severity])} ` +
    `${paint(f.rule, ANSI.bold)}  ${f.message}`;
  const out = [head];
  if (where) out.push(paint(`         ${where}`, ANSI.grey));
  if (f.detail) {
    for (const line of f.detail.split('\n')) out.push(paint(`         ${line}`, ANSI.dim));
  }
  out.push('');
  return out;
}

function countByRule(findings: Finding[]): Record<string, number> {
  const out: Record<string, number> = {};
  for (const f of findings) out[f.rule] = (out[f.rule] ?? 0) + 1;
  return out;
}

// ─────────────────────────────────────────────────────────────── markdown

export function renderMarkdown(input: ReportInput): string {
  const { snapshot, findings, diff, skipped = [] } = input;
  const health = computeHealth(snapshot, input.staleDays);
  const md: string[] = [];

  md.push(`# Integrity report — ${snapshot.takenAt.slice(0, 10)}`);
  md.push('');
  md.push(
    `Generated by \`mhka\` from the snapshot taken ${snapshot.takenAt.slice(0, 10)} ` +
      `(origin: ${snapshot.origin}). This tool reads and reports; it never writes to Notion.`
  );
  md.push('');

  md.push('## Suspicious changes since last run');
  md.push('');
  if (!diff) {
    md.push('_No comparison run. `mhka diff` needs two snapshots._');
  } else if (!diff.suspicious.length) {
    md.push(`_None._ Compared ${diff.from.slice(0, 10)} → ${diff.to.slice(0, 10)}.`);
  } else {
    md.push(`Compared ${diff.from.slice(0, 10)} → ${diff.to.slice(0, 10)}.`);
    md.push('');
    for (const f of diff.suspicious) md.push(...markdownFinding(f));
  }
  md.push('');

  for (const [heading, severity] of [
    ['Errors', 'error'],
    ['Warnings', 'warn'],
    ['Notes', 'info'],
  ] as const) {
    const group = findings.filter((f) => f.severity === severity);
    md.push(`## ${heading}`);
    md.push('');
    if (!group.length) {
      md.push('_None._');
    } else {
      for (const f of group) md.push(...markdownFinding(f));
    }
    md.push('');
  }

  if (skipped.length) {
    md.push('## Not run');
    md.push('');
    for (const s of skipped) md.push(`- **${s.id}** — ${s.why}`);
    md.push('');
  }

  md.push('## Corpus health');
  md.push('');
  md.push('```');
  for (const l of formatHealthLines(health)) md.push(l);
  md.push('```');
  md.push('');
  md.push(
    '> Counts, never a percentage or a score. A single health figure would invite ' +
      'optimising the number instead of the history, and would flatten exactly the ' +
      'distinction — between thin and strong evidence — that the base exists to preserve.'
  );
  md.push('');

  if (diff) {
    md.push('## Change volume');
    md.push('');
    md.push(`- Added: ${diff.additions.length}`);
    md.push(`- Edited: ${diff.edits.length}`);
    md.push(`- Removed: ${diff.removals.length}`);
    if (diff.additions.length) {
      md.push('');
      md.push('New records:');
      for (const a of diff.additions.slice(0, 40)) {
        md.push(`- \`${a.collection}\` ${a.title}`);
      }
    }
    md.push('');
  }

  return md.join('\n');
}

function markdownFinding(f: Finding): string[] {
  const where = [f.collection, f.slug, f.field].filter(Boolean).join(' / ');
  const out = [`- **${f.severity.toUpperCase()}** \`${f.rule}\` ${f.message}`];
  if (where) out.push(`  - \`${where}\``);
  if (f.detail) {
    for (const line of f.detail.split('\n')) {
      if (line.trim()) out.push(`  - ${line.trim()}`);
    }
  }
  return out;
}

// ─────────────────────────────────────────────────────────────────── json

export function renderJson(input: ReportInput): string {
  const health = computeHealth(input.snapshot, input.staleDays);
  return JSON.stringify(
    {
      takenAt: input.snapshot.takenAt,
      origin: input.snapshot.origin,
      findings: input.findings,
      suspicious: input.diff?.suspicious ?? [],
      changeVolume: input.diff
        ? {
            added: input.diff.additions.length,
            edited: input.diff.edits.length,
            removed: input.diff.removals.length,
          }
        : null,
      skipped: input.skipped ?? [],
      health,
    },
    null,
    2
  );
}

export type { Health };
